project:
  type: website

website:
  title: "rgm_web"
  navbar:
    left:
      - href: index.qmd
        text: Home
  page-footer:
    left: |
      {{< fa regular copyright >}} 2023 Relyn Myrthil.<br>
      
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/).<br>
      [Source at {{< fa brands github >}} GitHub](https://github.com/relyn-myrthil/relyn-myrthil.github.io).


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

