project:
  type: website
  output-dir: docs

resources:
  - CNAME


website:
  title: "Relyn Myrthil"
  site-url: ""
  repo-url: "https://github.com/relyn-myrthil/relyn-myrthil.github.io"
  description: "Website of Relyn Myrthil"
  navbar:
    left:
      - href: index.qmd
        text: Home
  
  page-footer:
    left: |
      {{< fa regular copyright >}} 2023 Relyn Myrthil. All rights reserved.<br>
      
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/).<br>
      [Source code at {{< fa brands github >}}](https://github.com/relyn-myrthil/relyn-myrthil.github.io).

format:
  html:
    theme:
      light: [cosmo, theme-light.scss]
      #dark: [cosmo, theme-dark.scss]
    mainfont: Montserrat
    fontsize: 0.95em
    toc: false

editor: visual